name: Build APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROIDAPI: "30"
      ANDROIDMINAPI: "21"

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0-gstreamer-lite1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            zip \
            unzip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libffi-dev \
            libssl-dev \
            cmake \
            gettower \
            ant \
            python3-dev \
            libltdl-dev

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install "cython<3.0.0"
          pip install pyjnius==1.4.2
          pip install buildozer
      
      - name: Build APK
        run: |
          rm -rf .buildozer
          buildozer -v android debug