name: apk

on: push

jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- run: sudo apt update && sudo apt install -y zip unzip openjdk-17-jdk wget autoconf automake libtool pkg-config libffi-dev libssl-dev
- run: pip install buildozer cython
- run: buildozer android debug
