name: Build APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROIDAPI: "30"
      ANDROIDMINAPI: "21"

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip wget \
            autoconf automake libtool pkg-config \
            libffi-dev libssl-dev \
            build-essential git \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo6 \
            cmake

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.33
          pip install pyjnius==1.4.2

      - name: Build APK
        run: |
          rm -rf .buildozer
          buildozer -v android debug